# Node labels to use to check the status of each stage
labels:
  aws-vpc-cni: node-role.kubernetes.io/aws-vpc
  cilium: node-role.kubernetes.io/cilium
  value: "true" # used as the value to each label key

# File paths of resources for the migration
paths:
  knet-stress: ./resources/knet-stress.yaml
  cilium-pre-migration: ./resources/cilium-pre-migration.yaml
  cilium-post-migration: ./resources/cilium-post-migration.yaml

awsVpcCni:
  namespace: kube-system
  daemonsetName: aws-node

clusterAutoscaler:
  namespace: kube-system
  deploymentName: cluster-autoscaler
  replicas: 1

cilium:
  release-name: cilium
  chart-name: cilium/cilium
  repo-path: "https://helm.cilium.io/"
  version: 1.12.5
  namespace: kube-system

# Resources required before any migration steps.
preflightResources:
  daemonsets:
    knet-stress:
    - knet-stress
    - knet-stress-2
  deployments:
  statefulsets:

# Resources to watch status for to ensure that the cluster is healthy at each
# stage. Must be installed and ready at prepare.
watchedResources:
  daemonsets:
    knet-stress:
    - knet-stress
    - knet-stress-2
  deployments:
  statefulsets:

# Resources to clean up at the end of the migration.
cleanUpResources:
  daemonsets:
    kube-system:
    knet-stress:
    - knet-stress
    - knet-stress-2
  deployments:
  statefulsets:
