# Node labels to use to check the status of each stage
labels:
  aws-vpc-cilium: node-role.kubernetes.io/aws-vpc
  cni-priority-aws-vpc: node-role.kubernetes.io/priority-aws-vpc
  cni-priority-cilium: node-role.kubernetes.io/priority-cilium
  rolled: node-role.kubernetes.io/rolled
  cilium: node-role.kubernetes.io/cilium
  migrated: node-role.kubernetes.io/migrated
  value: "true" # used as the value to each label key

# File paths of resources for the migration
paths:
  knet-stress: ./resources/knet-stress.yaml

# Resources required before any migration steps.
preflightResources:
  daemonsets:
    knet-stress:
    - knet-stress
    - knet-stress-2
  deployments:
  statefulsets:

# Resources to watch status for to ensure that the cluster is healthy at each
# stage. Must be installed and ready at prepare.
watchedResources:
  daemonsets:
    kube-system:
    - aws-node
    - cilium
    knet-stress:
    - knet-stress
    - knet-stress-2
  deployments:
  statefulsets:

# Resources to clean up at the end of the migration.
cleanUpResources:
  daemonsets:
    kube-system:
    - aws-node
    - cilium
    knet-stress:
    - knet-stress
    - knet-stress-2
  deployments:
  statefulsets:
